name: braz_web_page
description: A simple widget page template with hacks for web
version: 0.0.1
author: Emanuel Braz (fastencoding@gmail.com)
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.0.1
  flutter_mobx: ^1.0.1

  connectivity_web:
    git: https://github.com/emanuel-braz/connectivity_web.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
