name: braz_web_page
description: A simple widget page template with hacks for web
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.0.1
  flutter_mobx: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
